language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
install:
  - pip install coverage coveralls
  - pip install . --use-mirrors
script: coverage run tests/runtests.py
after_success:
  - coveralls
