language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
# command to install dependencies
install:
  - "pip install . --use-mirrors"
  - "pip install -r tests/test_requirements.txt --use-mirrors"
# command to run tests
before_script:
  - chmod +x tests/runtests.py
script: tests/runtests.py
